name: Release Linux Binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-gnu/release/check_local_memory_usage
          asset_name: check_local_memory_usage-linux-x86_64
          asset_content_type: application/octet-stream
